config/routes.rb
Rails.application.routes.draw do
  get 'books/top'
  get 'home/about'
  get 'books/edit'
  get 'search/search', as: 'search'
  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'follower' => 'users#follower'
    get 'followed' => 'users#followed'
  end

  root 'books#top'

  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: {minimum: 2, maximum: 20}
  validates :introduction, length: {maximum: 50}

  def email_required?
	false
  end

  # refileを使用
  attachment :profile_image

  has_many :books, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人


  # ユーザーをフォローする
def follow(user_id)
  follower.create(followed_id: user_id)
end

# ユーザーのフォローを外す
def unfollow(user_id)
  follower.find_by(followed_id: user_id).destroy
end

# フォローしていればtrueを返す
def following?(user)
  following_user.include?(user)
end

include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
     before_action :ensure_current_user, {only: [:edit,:update,:destroy]}
     #(ログインユーザー以外の情報を遷移しようとした時に制限をかける)


  def index
    @user = User.find(current_user.id)
    @users = User.all
    @book = Book.new
  end

  def show
    # ユーザーデータを取得
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    if @user.save
      NotificationMailer.send_confirm_to_user(@user).deliver
      redirect_to @user
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "User was successfully updated."
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end

  def destroy
  end


  def follower
    user = User.find(params[:user_id])
    @users = user.following_user
  end

  def followed
    user = User.find(params[:user_id])
    @users = user.follower_user
  end


  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def zipedit
    params.require(:user).permit(:postcode, :prefecture_name, :address_city, :address_street, :address_building)
  end

  def  ensure_current_user
        @user = User.find(params[:id])
     if @user.id != current_user.id
        redirect_to user_path(current_user.id)

     end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "img/no-image.png") %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_list.html.erb
<body>
	<div>

		<!-- New Book投稿フォーム -->
		<%= form_for (book) do |f| %>

		<!-- エラー時メッセージ表示 -->
			<div class="error_display">
				<% if book.errors.any? %>
					<h3><%= book.errors.count %> errors prohibited this obj from being saved:</h3>
					<ul>
						<% book.errors.full_messages.each do |message| %>
						<li><%= message %></li>
						<% end %>
					</ul>
				<% end %>
			</div>

			<div>
			<!-- ユーザー情報を表示 -->

			<h2>User info</h2>
			<%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "img/no-image.png", size: "100x100"  %>
			<table class="table table-hover table-inverse">
				<tr>
					<th>name</th>
					<td><%= user.name %></td>
				</tr>
				<tr>
					<th>introduction</th>
					<td><%= user.introduction %></td>
				</tr>
				<tr>
					<th>follows</th>
					<td><%= link_to user.follower.count, user_follower_path(user.id) %></td>
				</tr>
				<tr>
					<th>followers</th>
					<td><%= link_to user.followed.count, user_followed_path(user.id) %></td>
				</tr>

				<tr>
				  <td>
					<% if current_user.following?(user) %>
              <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST, class: "btn btn-primary" %>
              <% else %>
              <%= link_to 'フォローする', follow_path(user.id), method: :POST, class: "btn btn-success" %>
              <% end %>
					</td>
				</tr>
			</table>

			<!-- ユーザー編集画面へのリンク -->
			<% if @user.id == current_user.id %>
            <%= link_to edit_user_path(current_user.id) do %>
            <div class= " edit btn btn-outline-secondary btn-default btn-block" ><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></div>
            <% end %>
            <% end %>



				<!-- フォームの中身 -->
				<h2>New book</h2>
				<h4>Title</h4>
					<%= f.text_field :title, class: "book_title col-xs-12" %>
				<h4>Opinion</h4>
					<%= f.text_area :body, class: "book_body col-xs-12" %>
				<div>
					<%= f.submit 'Create Book', class: "btn btn-primary col-xs-12" %>
			</div>
		<% end %>
	</div>
</body>

app/views/users/edit.html.erb
<body>
	<div class="container">
		<div class="row">

			<section class="col-xs-12">
				<!-- New Book投稿フォーム -->
				<%= form_for (@user) do |f| %>

				<!-- エラー時メッセージ表示 -->
					<div class="error_display">
						<% if @user.errors.any? %>
							<h3><%= @user.errors.count %> errors prohibited this obj from being saved:</h3>
							<ul>
								<% @user.errors.full_messages.each do |message| %>
								<li><%= message %></li>
								<% end %>
							</ul>
						<% end %>
					</div>

					<p>User info</p>

					<!-- ユーザー編集画面表示 -->
					<h4>Name</h4>
						<%= f.text_field :name, class: "name" %>
					<h4>Image</h4>
			    		<%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user_image" %>
					<h4>Introduction</h4>
						<%= f.text_area :introduction, class: "introduction" %>
					<div>
						<%= f.submit 'Update User' %>
					</div>
				<% end %>
			</section>

	</div>
</body>

app/views/users/followed.html.erb
<body>
<h2>Follower Users</h2>
<div class="container">
		<div class="row">

			<section class="col-xs-12">
<table class="table table-hover table-inverse">
<thead>
						<tr>
							<th>image</th>
							<th>name</th>
							<th></th>
						</tr>
					</thead>
					<% @users.each do |user| %>
					<tbody>
						<tr>
							<td>
								<%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "img/no-image.png", size: "50x50" %>
							</td>
							<td><%= user.name %></td>
							<td><%= "フォロー数: #{user.follower.count}" %></td>
							<td><%= "フォロワー数: #{user.followed.count}" %></td>

							

							<td><%= link_to "Show", user_path(user.id), class: "user_#{user.id}" %></td><br>
							
						</tr>
					</tbody>
          <% end %>
</table>
</section>
</div>
</div>
</body>

app/views/users/follower.html.erb
<body>
<h2>Follow Users</h2>
<div class="container">
		<div class="row">

			<section class="col-xs-12">
<table class="table table-hover table-inverse">
<thead>
						<tr>
							<th>image</th>
							<th>name</th>
							<th></th>
						</tr>
					</thead>
					<% @users.each do |user| %>
					<tbody>
						<tr>
							<td>
								<%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "img/no-image.png", size: "50x50" %>
							</td>
							<td><%= user.name %></td>
							<td><%= "フォロー数: #{user.follower.count}" %></td>
							<td><%= "フォロワー数: #{user.followed.count}" %></td>

					

							<td><%= link_to "Show", user_path(user.id), class: "user_#{user.id}" %></td>
							
						</tr>
					</tbody>
          <% end %>
          </table>
          </section>
          </div>
          </div>

</body>

app/views/users/index.html.erb
<body>
	<div class="container">
		<div class="row">

			<section class="col-xs-3">
				<!-- ユーザー情報と投稿フォームを表示 -->
				<%= render 'users/list', book: @book, user: @user %>
			</section>

			<section class="col-xs-9">
				<h1>Users</h1>

				<!-- ユーザー一覧を表示 -->
				<table class="table table-hover table-inverse">
					<thead>
						<tr>
							<th>image</th>
							<th>name</th>
							<th></th>
						</tr>
					</thead>
					<% @users.each do |user| %>
					<tbody>
						<tr>
							<td>
								<%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "img/no-image.png", size: "50x50" %>
							</td>
							<td><%= user.name %></td>
							<td><%= "フォロー数: #{user.follower.count}" %></td>
							<td><%= "フォロワー数: #{user.followed.count}" %></td>

							<td>
							<% if current_user.following?(user) %>
              <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
              <% else %>
              <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
              <% end %>
							</td>

							<td><%= link_to "Show", user_path(user.id), class: "user_#{user.id}" %></td>
							
						</tr>
					</tbody>
					<% end %>
				</table>
			</section>

		</div>
	</div>
</body>

app/views/users/show.html.erb
<body>
	<div class="container">
		<div class="row">
			<!-- サクセスメッセージ表示 -->
			<p>
				<% if flash[:notice] %>
					<%= flash[:notice] %>
				<% end %>
			</p>

			<section class="col-xs-3">
				<!-- ユーザー情報と投稿フォームを表示 -->
				<%= render 'users/list', book: @book, user: @user %>
			</section>

			<section class="col-xs-9">

				<h1>Books</h1>

				<!-- 投稿内容を表示 -->
				<table class="table table-hover table-inverse">
					<thead>
						<tr>
							<th></th>
							<th>Title</th>
							<th>Opinion</th>
						</tr>
					</thead>
					<% @books.each do |book| %>
					<tbody>
						<tr>
							<td>
								<%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, fallback: "img/no-image.png", size: "50x50" %>
							</td>
							<td><%= link_to book.title, book_path(book.id), class: "book_#{book.id}" %></td>
							<td><%= book.body %></td>
						</tr>
					</tbody>
					<% end %>
				</table>
				<div id='map'></div>

<style>
#map{
  height: 400px;
}
</style>

				<script>
				

function initMap(){
	var geocoder = new google.maps.Geocoder();

	geocoder.geocode({ address: "<%= @user.address_city %>" }, function(results, status){
   if (status === 'OK' && results[0]){  //status を確認して処理開始
      new google.maps.Map(document.getElementById('map'), {
        center: results[0].geometry.location,
        zoom: 14
      });
   }else{
     alert('失敗しました。理由: ' + status);
   }
}); 

 
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCJFk8qRbKA5Z94FIn6LL1E3MvgwDWMlfA&callback=initMap" async defer></script>
			</section>
			
		</div>
	</div>
</body>