config/routes.rb
Rails.application.routes.draw do
  get 'books/top'
  get 'home/about'
  get 'books/edit'
  get 'search/search', as: 'search'
  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'follower' => 'users#follower'
    get 'followed' => 'users#followed'
  end

  root 'books#top'

  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す


end

app/models/book.rb
class Book < ApplicationRecord
	# タイトル・感想文未入力時にエラー表示
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
	
	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :post_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

	
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

before_action :ensure_current_user, {only: [:edit,:update,:destroy]}

  def top
  end

  def about
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      @user = User.find(current_user.id)
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @post_comment = PostComment.new
  end

  def index
    @user = User.find(current_user.id)
    @book = Book.new
    @books = Book.all
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user.id != current_user.id
      redirect_to book_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      flash[:notice] = "Book was successfully destroyed."
      redirect_to books_path
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def  ensure_current_user
      @book = Book.find(params[:id])
     if @book.user_id != current_user.id
        redirect_to books_path
     end
  end


end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_comment.html.erb
<td>
コメント数：<%= book.post_comments.count %>
</td>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr> 
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "img/no-image.png") %>
          <% end %>
        </td>
        <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_post.html.erb
<% if book.favorited_by?(current_user) %>
  
     <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
     <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
     <%= book.favorites.count %>
     <% end %>

  <% else %>
  <td>
     <%= link_to book_favorites_path(book), method: :post,  remote: true do %>
     <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
     <%= book.favorites.count %>
     <% end %>
  
<% end %>

app/views/books/_post_comment.html.erb
<% @book.post_comments.each do |post_comment| %>
				<table>
        <tr>
				    <td>
							<%= attachment_image_tag @book.user, :profile_image, :fill, 50, 50, fallback: "img/no-image.png", size: "50x50" %>
						</td>
						<td><%= post_comment.comment %></td>
						<td>
						<% if post_comment.user == current_user %>
            <div>
              <%= link_to "Destroy", book_post_comment_path(post_comment.book, post_comment), method: :delete, class: "btn btn-danger pull-right", remote: true %>
            </div>
          <% end %>
						</td>
				<% end %>
				</tr>
				</table>

app/views/books/edit.html.erb
<body>
	<div class="container">
		<div class="row">
			<div class="col-md-6 col-md-offset-3">
		<%= form_for (@book) do |f| %>

		<!-- エラー時メッセージ表示 -->
			<% if @book.errors.any? %>
				<h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
				<ul>
					<% @book.errors.full_messages.each do |message| %>
					<li><%= message %></li>
					<% end %>
				</ul>
			<% end %>

			<h2>Editing Book</h2>
			<h4>Title</h4>
				<%= f.text_field :title, class: "book_title col-xs-12" %>
			<h4>Opinion</h4>
				<%= f.text_area :body, class: "book_body col-xs-12" %>
			<div>
				<%= f.submit 'Update Book', class: "btn btn-primary col-xs-12" %>
			</div>
		<% end %>

		<div class="btn btn-sm">
		<%= link_to "Show", book_path, class: "book_#{@book.id}" %>
		</div>

		<div class="btn btn-sm">
		<%= link_to "Back", books_path, class: "back" %>
		</div>
	</div>
	</div>
	</div>
</body>

app/views/books/index.html.erb
<body>
	<div class="container">
		<div class="row">

			<!-- サクセスメッセージ表示 -->
			<p>
				<% if flash[:notice] %>
					<%= flash[:notice] %>
				<% end %>
			</p>

			<section class="col-xs-3">
				<!-- ユーザー情報と投稿フォームを表示 -->
				<%= render 'users/list', book: @book, user: @user %>
			</section>

			<section class="col-xs-9">
				<h1>Books</h1>

				<!-- 投稿一覧を表示 -->
				<table class="table table-hover table-inverse">
					<thead>
						<tr>
							<th></th>
							<th>Title</th>
							<th>Opinion</th>
						</tr>
					</thead>
					<% @books.each do |book| %>
					<tbody>
						<tr>
							<td>
								<%= link_to user_path(book.user_id) do %>
								<%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, fallback: "img/no-image.png", size: "50x50" %>
							</td>
							<% end %>

							<td><%= link_to book.title, book_path(book.id), class: "book_#{book.id}" %></td>
							<td><%= book.body %></td>
							

							<td id="favorite_<%= book.id %>">
								<%= render 'books/post', book: book %>
							</td>
							<%= render 'books/comment', book: book %>

						</tr>
					</tbody>
					<% end %>
				</table>
			</section>

		</div>
	</div>
</body>

app/views/books/show.html.erb
<body>
	<div class="container">
		<div class="row">

			<!-- サクセスメッセージ表示 -->
			<p>
				<% if flash[:notice] %>
					<%= flash[:notice] %>
				<% end %>
			</p>

			<section class="col-xs-3">
				<!-- ユーザー情報と投稿フォームを表示 -->
				<%= render 'users/list', book: Book.new, user: @user %>
			</section>


			<section class="col-xs-9">
				<h1>Book detail</h1>

				<!-- 投稿内容を表示 -->
				<table class="table table-hover table-inverse">
					<tr>
						<td>
							<%= attachment_image_tag @book.user, :profile_image, :fill, 50, 50, fallback: "img/no-image.png", size: "50x50" %>
						</td>
						<td><%= @book.title %></td>
						<td><%= @book.body %></td>

						<td id="favorite_<%= @book.id %>">
								<%= render 'books/post', book: @book %>
						</td>
						<%= render 'books/comment', book: @book %>

						<!-- 編集・削除 条件分岐 -->
						<% if @book.user.id == current_user.id %>
							<td>
								<%= link_to "Edit", edit_book_path, class: "edit_book_#{@book.id} btn btn-sm btn-success" %>
							</td>

							<td>
								<%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に消しますか？", class: "destroy_book_#{@book.id} btn btn-sm btn-danger" %>
							</td>
						<% end %>
					</tr>
				</table>

				<!-- ユーザー詳細画面へのリンク -->
				
				<tr>
				<td>
				<%= link_to @user.name, user_path(@user.id), class: "user_#{@user.id}" %>
				</td>
				</tr>



				<!-- コメント -->
				<ul>
				<li id="post_comments">
            <%= render partial: 'books/post_comment', locals: { book: @book, post_comment: @post_comment } %>
        </li>
				</ul>


			  			
				<%= form_with(model: [@book, @post_comment], url: book_post_comments_path(@book) ) do |f| %>
        <%= f.text_area :comment, class: "input-mysize" %>
        <%= f.submit "送信", class: "btn btn-outline-dark comment-submit float-right" %>
        <% end %>





			</section>
		</div>
	</div>
</body>

app/views/books/top.html.erb
<body>
	<div class="container">
		<div class="row">
			<div class="col-md-6 col-md-offset-3">
	<!-- サクセスメッセージ表示 -->
		<p>
			<% if flash[:notice] %>
				<%= flash[:notice] %>
			<% end %>
		</p>

	<!-- 本文 -->
		<h1>	welcome to
			<section class="glyphicon glyphicon-book"></section>
			<strong>Bookers</strong>
			!!
		</h1>
		<h4>	In
			<section class="glyphicon glyphicon-book"></section>
			<strong>Bookers</strong>
			,
		</h4>
		<p>you can share and exchange your opinions , inpressions , and emotions
		</p>
		<p>about varioius books!</p>
		<p class="btn btn-info col-xs-10 col-xs-offset-1">
			<%= link_to "Log in", new_user_session_path, class: "sign_in" %>
		</p>
		<p class="btn btn-success col-xs-10 col-xs-offset-1">
			<%= link_to "Sign up", new_user_registration_path, class: "sign_up" %>
		</p>
	</div>
    </div>
	</div>
</body>